Added book details view
wolox-training/gz-vue pull request #2
Opened 2019-09-11 19:09 UTC by gzamudio

### Summary
- Added book details view

### Screenshots
<img width="354" alt="Captura de Pantalla 2019-09-11 a la(s) 16 08 39" src="https://user-images.githubusercontent.com/1482005/64727126-8575d200-d4ae-11e9-9715-9935fca8fe5b.png">

### Trello Card
- https://trello.com/c/zwEIfpjG

2019-09-11 20:52 UTC, BJordi requested changes

2019-09-11 20:52 UTC, BJordi commented on scss/colors.scss
> +$gray: #828282;
Add empty line at the end of the file.

2019-09-11 20:52 UTC, BJordi commented on scss/details.scss
> +	color: $gray;
Fix indentation.

2019-09-11 20:52 UTC, BJordi commented on scss/details.scss
> +	color: $gray;
Use 2 spaces per tab.

2019-09-11 20:52 UTC, BJordi commented on scss/details.scss
> +	font-weight: bold;
Sort it in non-descending order.

2019-09-11 20:52 UTC, BJordi commented on scss/details.scss
> +		margin: 24px 0 34px 0;
Is that difference between 24 and 34 needed?

2019-09-11 20:52 UTC, BJordi commented on scss/styles.scss
> +    display: flex;
Sort it and add a `margin: 0`.

2019-09-11 20:52 UTC, BJordi commented on index.html
> +  <p class="book-prop">Título del libro: <span class="book-prop-value">(género)</span></p>
Instead of using a `span` tag inside the `p` tag, it's better to have an `h` tag with a `span` one as siblings and a parent div with `display: flex`.

2019-09-12 12:06 UTC, nvescio requested changes

2019-09-12 12:06 UTC, nvescio commented on scss/details.scss
> +	font-size: 20px;
Fix indentation here

2019-09-12 12:06 UTC, nvescio commented on scss/styles.scss
> +    display: flex;
Change indentation to 2 spaces

2019-09-12 12:06 UTC, nvescio commented on scss/details.scss
> +  font-weight: normal;
It's not necessary, `normal` is the default value for `font-weight`.

2019-09-17 19:49 UTC, BJordi approved these changes

2019-09-17 22:16 UTC, merged