Added image
wolox-training/gz-vue pull request #3
Opened 2019-09-11 19:35 UTC by gzamudio

### Summary
- Added image to book details

### Screenshots
![Uploading Captura de Pantalla 2019-09-11 a la(s) 16.34.12.png…]()

### Trello Card
- https://trello.com/c/uhdwuZai

2019-09-11 20:56 UTC, BJordi requested changes

2019-09-11 20:56 UTC, BJordi commented on scss/details.scss
> +	display: flex;
Sort indentation.

2019-09-11 20:56 UTC, BJordi commented on scss/details.scss
> +	display: flex;
What you can do is create a `display.scss` file under the path `src/scss/common/`. In that file you can create common classes used to display different things that are very boilerplate:
```scss
.row {
  display: flex;
  flex-direction: row;
}

.column {
  display: flex;
  flex-direction: column;
}

2019-09-11 20:56 UTC, BJordi commented on index.html
> +    <p class="book-prop">Título del libro: <span class="book-prop-value">(género)</span></p>
Do as mentioned in the previous PR.

2019-09-12 12:11 UTC, nvescio requested changes

2019-09-12 12:11 UTC, nvescio commented on scss/common.scss
> +	display: flex;
Fix indentation here

2019-09-12 12:11 UTC, nvescio commented on scss/common.scss
> +}
Add an empty line here to avoid this error.

2019-09-12 12:11 UTC, nvescio commented on scss/details.scss
> +img {
Try not to style `img` tag, it's better to add a class for the image.

2019-09-17 19:52 UTC, BJordi requested changes

2019-09-17 19:52 UTC, BJordi commented on scss/details.scss
> +	width: 33%;
Fix indentation.

2019-09-17 19:52 UTC, BJordi commented on scss/styles.scss
> +  margin: auto;
`margin: 0;`

2019-09-19 12:40 UTC, nvescio approved these changes

2019-10-09 12:19 UTC, merged