Added details structure
wolox-training/gz-vue pull request #4
Opened 2019-09-13 22:19 UTC by gzamudio

### Summary
- Added details structure

### Screenshot
<img width="1022" alt="Captura de Pantalla 2019-09-13 a la(s) 19 17 55" src="https://user-images.githubusercontent.com/1482005/64897853-48027780-d65b-11e9-8f2f-e4d817b90ea7.png">

### Trello Card
- https://trello.com/c/Fvotr4lC

2019-09-17 11:46 UTC, nvescio requested changes

2019-09-17 11:46 UTC, nvescio commented on scss/details.scss
> +    padding: 0 0 12px 0;
I'd use `padding-bottom: 12px;` here

2019-09-17 11:46 UTC, nvescio commented on scss/details.scss
> +  box-shadow: 4px 4px 10px 0 rgba(0,0,0,0.5);
Try to leave a space after the commas --> `rgba(0, 0, 0, 0.5)`

2019-09-17 19:58 UTC, BJordi requested changes

2019-09-17 19:58 UTC, BJordi commented on scss/details.scss
> +  width: 1000px;
Sort it.

2019-09-17 19:58 UTC, BJordi commented on scss/details.scss
> +  width: 1000px;
Why not `width: 100%;`? :thinking:

2019-09-19 12:41 UTC, nvescio approved these changes

2019-10-09 12:25 UTC, merged